add uniq tool and update .gitignore
tiago4orion/enzo pull request #27
Opened 2017-01-01 13:39 UTC by geyslan

2017-01-03 23:03 UTC, i4ki requested changes
I just added some style notes.
The logic is more complex than I expected and because of that very hard to get mistakes in simple review.

I'll add some tests to both PRs to make sure it comply with #29 .

2017-01-03 23:03 UTC, tiago4orion commented on cmd/uniq/uniq.go
> +		lineBytes, err := reader.ReadBytes(byte('\n'))
must check error.

2017-01-03 23:03 UTC, tiago4orion commented on cmd/uniq/uniq.go
> +		lineCount := len(lineNumsMap[lineP])
lineLen is a better naming and consistency with your `lineMapLen`.

2017-01-03 23:03 UTC, tiago4orion commented on cmd/uniq/uniq.go
> +	inputMap := make(map[string]*string)
maybe call it inputStrPtr to mean the storage of string pointers?

2017-01-03 23:03 UTC, tiago4orion commented on cmd/uniq/uniq.go
> +	lineNumsMap := make(map[*string][]int)
lineNumbers ?

There are 3 maps here. I don't think reader could misinterpret the content of variable.

2017-01-03 23:03 UTC, tiago4orion commented on cmd/uniq/uniq.go
> +		var lineP *string
Camelcase only to glue words. Better to use `linep`, or `lineptr`.

2017-01-03 23:03 UTC, tiago4orion commented on cmd/uniq/uniq.go
> +		if val, has := inputMap[line]; has {
You can avoid the extra branching and save few lines making 'linep := &line` by default and overwriting only if it's already in the map.

2017-01-03 23:03 UTC, tiago4orion commented on cmd/uniq/uniq.go
> +func uniq(input *os.File, opts options) {
why everything in the same function? Too much context, lots of variables in same scope, etc. Hard to read.

Breaking in several functions do not hurt, functions are inlined in some cases. Maps and slices are references, never copied if passed as parameters or returned from functions.

2017-01-03 23:03 UTC, tiago4orion commented on cmd/uniq/uniq.go
> +		numbersCount := len(lineNumbers)
numbersCount is used 1x. Use len(lineNumbers) in place.

2017-01-03 23:43 UTC, geyslan commented on cmd/uniq/uniq.go
> +func uniq(input *os.File, opts options) {
Sure. It was just laziness during housekeeping. Will be dismembered.

2017-01-03 23:44 UTC, geyslan commented on cmd/uniq/uniq.go
> +	inputMap := make(map[string]*string)
Ok.

2017-01-03 23:47 UTC, geyslan commented on cmd/uniq/uniq.go
> +	lineNumsMap := make(map[*string][]int)
Let us see if the `linesOrdered` slice suggested in https://github.com/c0defellas/enzo/pull/28#issuecomment-270253257 can suplant those maps.

2017-01-03 23:48 UTC, geyslan commented on cmd/uniq/uniq.go
> +		lineBytes, err := reader.ReadBytes(byte('\n'))
Ok.

2017-01-03 23:49 UTC, geyslan commented on cmd/uniq/uniq.go
> +		var lineP *string
Nice.

2017-01-03 23:50 UTC, geyslan commented on cmd/uniq/uniq.go
> +		lineCount := len(lineNumsMap[lineP])
I see. But in this case. lineCount is the count of lines not the length of a line. It can be confusing to use lineLen.

2017-01-03 23:52 UTC, geyslan commented on cmd/uniq/uniq.go
> +		numbersCount := len(lineNumbers)
In the loop won't it be evaluated in each iteration?

2017-01-04 00:00 UTC, tiago4orion commented on cmd/uniq/uniq.go
> +		lineCount := len(lineNumsMap[lineP])
Ah, sorry ;)
I frequently forget `len` is a generic function.

2017-01-04 00:03 UTC, tiago4orion commented on cmd/uniq/uniq.go
> +		numbersCount := len(lineNumbers)
It will, but len do not count because strings are immutable. Golang string store its length internally, then len just access it.

2017-01-04 00:12 UTC, geyslan commented on cmd/uniq/uniq.go
> +		numbersCount := len(lineNumbers)
Hmm. I see. I'll compare their assembly later.

2017-01-04 11:26 UTC, geyslan commented
@tiago4orion before anything, let's discuss this on https://github.com/c0defellas/enzo/issues/29.

2017-01-22 00:52 UTC, geyslan commented
Closing this.
See PR https://github.com/c0defellas/enzo/pull/28.

2017-01-22 00:52 UTC, closed without merging